[versions]
agp = "8.13.1"
kotlin = "2.2.21"
protobuf = "0.9.4"
protobuf-kotlin = "3.25.5"
ktx-lifecycle = "2.10.0"

[libraries]
# AndroidX Core
androidx-ktx = { group = "androidx.core", name = "core-ktx", version = "1.17.0" }
runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "ktx-lifecycle" }
runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "ktx-lifecycle" }
androidx-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "ktx-lifecycle" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version = "1.12.1" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version = "1.2.0" }

# Compose
# https://central.sonatype.com/artifact/dev.chrisbanes.compose/compose-bom/versions
# compose-bom-alpha = { group = "dev.chrisbanes.compose", name = "compose-bom", version = "2024.05.00-alpha03" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version = "2025.12.00" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

# Streaming
protobuf-gradle-plugin = { module = "com.google.protobuf:protobuf-gradle-plugin", version.ref = "protobuf" }
protobuf-java-lite = { group = "com.google.protobuf", name = "protobuf-javalite", version.ref = "protobuf-kotlin" }

# Test
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version = "1.10.2" }
test-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version = "1.3.0" }
androidx-runner = { group = "androidx.test", name = "runner", version = "1.7.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-protobuf = { id = "com.google.protobuf", version.ref = "protobuf" }